name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [
            linux,
            windows,
            macos
        ]

        include:
          - name: linux
            os: ubuntu-latest
            artifact_name: visual
            asset_name: visual-linux
          - name: windows
            os: windows-latest
            artifact_name: visual.exe
            asset_name: visual-windows.exe
          - name: macos
            os: macos-latest
            artifact_name: visual
            asset_name: visual-macos

          - name: linux coco
            os: ubuntu-latest
            artifact_name: coco
            asset_name: coco-linux
          - name: windows coco
            os: windows-latest
            artifact_name: coco.exe
            asset_name: coco-windows.exe
          - name: macos coco
            os: macos-latest
            artifact_name: coco
            asset_name: coco-macos

    steps:
      - uses: actions/checkout@v1

      - name: Install Just
        run: cargo install just

      - name: Install wget for Windows
        run:  |
          if [ "$RUNNER_OS" == "Windows" ]; then
              choco install wget --no-progress
          fi
        shell: bash

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Build
        run:  |
          if [ "$RUNNER_OS" == "Windows" ]; then
              cargo build --target=i686-pc-windows-gnu --release
          else
              just release
          fi
      shell: bash

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}

